// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/calc.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/r3f-test.tsx";
import * as $$0 from "./islands/Calc.tsx";
import * as $$1 from "./islands/R3fTest.tsx";
import * as $$2 from "./islands/Root.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/calc.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/r3f-test.tsx": $4,
  },
  islands: {
    "./islands/Calc.tsx": $$0,
    "./islands/R3fTest.tsx": $$1,
    "./islands/Root.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
